### ISSUE TITLE
Update recipe

### ISSUE THREAD

**Issue by mfansler** [conda-forge/featurewiz-feedstock#38]
This is a placeholder/reminder to have a look at this recipe, re: https://github.com/conda-forge/staged-recipes/issues/27507.

Please ping me if I don't check back in on this within a week.

**Comment by arturdaraujo** [comment]
I used grayskull to create the recipe but I don't see any changes. I'm not sure if this PR is in the correct place.

https://github.com/arturdaraujo/staged-recipes/commit/eb1073099e097e262f0a1995d8e5d7ac16030a52

**Comment by arturdaraujo** [comment]
I think I got it now. I updated the recipe directly in featurewiz-feedstock.
https://github.com/conda-forge/featurewiz-feedstock/commit/ae6601f8e4783fef9f7fc4c8b62de719deceede2

**Comment by marcelotrevisani** [comment]
it should be fixed with #39

**Comment by arturdaraujo** [comment]
Just merged! Thank you guys so much!

**Comment by mfansler** [comment]
> I think I got it now. I updated the recipe directly in featurewiz-feedstock. [ae6601f](https://github.com/conda-forge/featurewiz-feedstock/commit/ae6601f8e4783fef9f7fc4c8b62de719deceede2)

Please review the Maintainer documentation: https://conda-forge.org/docs/maintainer/updating_pkgs/#forking-and-pull-requests

Users should never push to `main` or to anything in the feedstock directly. Instead, you are expected to use a personal fork, use a branch on that fork, then submit that as a PR to the feedstock.

> Just merged! Thank you guys so much!

As mentioned elsewhere (https://github.com/conda-forge/status/issues/188) there is a widespread outage of PR build jobs. The PR did not actually run any checks to see that the suggested updates were working. Turns out [they weren't](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1065844&view=logs&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&t=9eb77fd2-8ddd-5444-8fc0-71cb28dcb736&l=631). I would ask that you please wait until that situation is resolved.

**Comment by arturdaraujo** [comment]
Sorry, I will wait

**Comment by mfansler** [comment]
This first needs https://github.com/conda-forge/lazytransform-feedstock/pull/19.

**Comment by arturdaraujo** [comment]
Is there anything that I can do on my end now that lazytransform is updated?

**Comment by mfansler** [comment]
@arturdaraujo as a first attempt, there should be a "Re-run" button/link that you can click on the previous failed build attempt: https://github.com/conda-forge/featurewiz-feedstock/runs/32164285178

**Comment by mfansler** [comment]
If that doesn't work, then we might need a new PR to make further adjustments.

**Comment by arturdaraujo** [comment]
It failed
![Image](https://github.com/user-attachments/assets/954cbd92-e8f9-4ab1-955f-0fa039696b48)
